---

- name: "Play to test some variable substition"
  hosts: "192.168.0.102"
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Task 1"
      cisco.ios.ios_config:
        src: "bgp.j2"
        